### ISSUE TITLE
Product Backlog priorizado

### ISSUE THREAD

**Issue by darox47** [sefatecol/SFTLeishmaniasis#1]
_**Product Backlog priorizado con las historias de usuario para trabajar en el sprint 1._

- [x] Definir el product backlook priorizado en el formato Excel.
- [x] Subir el archivo al repositorio en GitHub

**Comment by ftorob** [comment]
@darox47 se creó una nueva branch con el nombre "Documentacion" para subir los archivos que se generen del proyecto. Pero también veo que aquí se pueden adjuntar documentos jejeje

[Historias De Usuario STFLeishmaniasis - BD.pdf](https://github.com/sefatecol/SFTLeishmaniasis/files/7118031/Historias.De.Usuario.STFLeishmaniasis.-.BD.pdf)
