### ISSUE TITLE
Historias de Usuario

### ISSUE THREAD

**Issue by darox47** [sefatecol/SFTLeishmaniasis#4]
- [x] Obtener las historias de usuario.
- [x] Registrar las historias de usuario en el formato Excel dispuesto.
- [x] Subir al repositorio el archivo con las historias de usuario-

**Comment by ftorob** [comment]
@darox47 Se pueden subir adjuntar documentos en el comentario 😲

[Historias De Usuario STFLeishmaniasis - BD.pdf](https://github.com/sefatecol/SFTLeishmaniasis/files/7118033/Historias.De.Usuario.STFLeishmaniasis.-.BD.pdf)
